export enum StockTransactionType {
  OPENING_BALANCE = 'OPENING_BALANCE',
  STOCK_IN = 'STOCK_IN',
  ADJUSTMENT_PLUS = 'ADJUSTMENT_PLUS',
  ADJUSTMENT_MINUS = 'ADJUSTMENT_MINUS',
  ISSUE_GIVEAWAY = 'ISSUE_GIVEAWAY',
}
